"""Bundled offline SVG report. All input labels are inserted through textContent."""

HTML_TEMPLATE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SeqAttn · Activation memory timeline</title>
<style>
:root{color-scheme:light;--ink:#172a3a;--muted:#647586;--line:#dae3e9;--teal:#137f7b;--bg:#f3f6f8}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px system-ui,sans-serif}
main{max-width:1520px;margin:auto;padding:30px 34px 60px}h1{font-size:30px;font-weight:650;margin:6px 0 10px}
h2{font-size:18px;margin:0 0 8px}h3{font-size:14px;margin:0 0 8px}.eyebrow{color:var(--teal);font-size:12px;letter-spacing:2px}
p{line-height:1.6}.muted{color:var(--muted)}.toolbar,.cards,.legend{display:flex;gap:16px;align-items:center;flex-wrap:wrap}
.toolbar{background:white;border:1px solid var(--line);padding:16px;border-radius:12px;margin:20px 0}
label{display:flex;gap:8px;align-items:center}select,button,input[type=text]{border:1px solid var(--line);border-radius:6px;background:white;padding:8px;color:var(--ink)}
select{max-width:650px}button{cursor:pointer}button:hover{border-color:var(--teal)}input[type=range]{width:135px;accent-color:var(--teal)}
.cards{align-items:stretch;margin:20px 0}.card{min-width:190px;flex:1;background:white;border:1px solid var(--line);border-radius:10px;padding:17px}
.card strong{display:block;font-size:23px;margin:7px 0}.card small{color:var(--muted)}.panel{background:white;border:1px solid var(--line);border-radius:12px;padding:20px;margin-top:18px}
.panel-title{display:flex;justify-content:space-between;align-items:center;gap:12px}.chart svg{display:block;width:100%;min-width:740px}.chart{overflow-x:auto}
.legend{gap:12px;font-size:12px;margin:12px 0 4px}.swatch{display:inline-block;width:11px;height:11px;border-radius:3px;margin-right:5px}
.warning{color:#ac4c14}.badge{font-size:11px;letter-spacing:1px;border-radius:4px;background:#e3f3f1;color:#12615d;padding:5px 8px}
#cursor-info{white-space:pre-wrap;line-height:1.6;background:#f5f8fa;border-radius:8px;padding:12px;margin-top:12px;min-height:54px}
#tooltip{position:fixed;display:none;max-width:470px;pointer-events:none;white-space:pre-wrap;background:#172a3a;color:white;padding:11px 14px;border-radius:8px;z-index:10;line-height:1.6;font-size:12px}
#lifetimes{max-height:600px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px;margin-top:14px}th,td{text-align:left;padding:9px 12px;border-bottom:1px solid var(--line)}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}
pre{white-space:pre-wrap;font:12px ui-monospace,monospace;line-height:1.6}details{margin-top:14px}summary{cursor:pointer;color:var(--muted)}
@media(max-width:760px){main{padding:18px 12px}.toolbar{gap:10px}h1{font-size:25px}.panel{padding:12px}}
</style></head><body><main>
<div class="eyebrow">SEQATTN / RESOURCE ESTIMATION</div>
<h1>Activation memory, over time</h1>
<p class="muted">Compute, I/O and physical allocation lifetimes share one clock. Persistent buffers remain allocated while idle.</p>
<div class="toolbar">
<label>Candidate <select id="candidate"></select></label><span id="status" class="badge"></span>
<button id="json-export">Export JSON</button><button id="reset">Reset view</button>
<label>Start <input id="range-start" type="range" min="0" max="99" value="0"></label>
<label>End <input id="range-end" type="range" min="1" max="100" value="100"></label>
</div><div id="selection-note" class="muted"></div><div id="cards" class="cards"></div>
<section class="panel"><div class="panel-title"><h2>Compute & I/O</h2><button id="svg-export">Export SVG</button></div>
<div class="toolbar"><label>Memory backdrop <select id="backdrop"></select></label><label><input id="show-backdrop" type="checkbox" checked> Show</label></div>
<div id="operations" class="chart"></div><div id="cursor-info">Move over a chart to inspect all storage pools at the same time.</div></section>
<div id="memory-panels"></div>
<section class="panel"><h2>Physical buffer lifetimes</h2><p class="muted">Pale bars show allocated lifetime; solid sections show declared use. One row represents one physical allocation, including its aliases.</p>
<div class="toolbar"><label>Pool <select id="lifetime-pool"></select></label><label>Filter <input id="buffer-filter" type="text" placeholder="Q, staging, FFN…"></label></div>
<div id="lifetimes" class="chart"></div></section>
<section class="panel"><h2>Model & provenance</h2><p id="source-note"></p><ul id="assumptions"></ul><details><summary>Parameters and calibration sources</summary><pre id="metadata"></pre></details></section>
</main><div id="tooltip"></div><script id="report-data" type="application/json">__REPORT_JSON__</script>
<script>
'use strict';
const DATA=JSON.parse(document.getElementById('report-data').textContent), $=id=>document.getElementById(id);
const NS='http://www.w3.org/2000/svg', W=1360, LEFT=210, RIGHT=30, PLOT=W-LEFT-RIGHT;
const palette=['#277d96','#579dce','#1c9989','#75b7a4','#cba052','#d57a54','#9778b0','#b66f8b','#63849c','#9d9f64','#59746a','#ab8870'];
let trace,stats,start=0,end=1,colors=new Map(),cursor=null;
const components=[...new Set(DATA.candidates.flatMap(c=>c.trace.buffers.map(b=>b.component).concat(c.trace.operations.map(o=>o.component))))].sort();
components.forEach((name,i)=>colors.set(name,palette[i%palette.length]));
const color=name=>colors.get(name)||'#7d929f', ms=t=>(t*1000).toFixed(3)+' ms';
const bytes=n=>n>=2**30?(n/2**30).toFixed(2)+' GiB':n>=2**20?(n/2**20).toFixed(2)+' MiB':n>=1024?(n/1024).toFixed(1)+' KiB':n+' B';
function el(tag,attrs={},text){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e}
function html(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function option(select,value,text){const o=html('option',text);o.value=value;select.append(o)}
function x(t){return LEFT+(t-start)/(end-start)*PLOT}
function frame(height){const svg=el('svg',{viewBox:`0 0 ${W} ${height}`,role:'img',style:'font:12px system-ui,sans-serif;background:white'});return svg}
function axes(svg,top,bottom){for(let i=0;i<=8;i++){const px=LEFT+i*PLOT/8,t=start+i*(end-start)/8;svg.append(el('line',{x1:px,x2:px,y1:top,y2:bottom,stroke:'#e9eef2'}));svg.append(el('text',{x:px,y:bottom+22,fill:'#647586','text-anchor':'middle'},ms(t)));}}
function rect(svg,a,b,y,h,fill,opacity=1){const lo=Math.max(a,start),hi=Math.min(b,end);if(hi<=lo)return null;const r=el('rect',{x:x(lo),y,width:Math.max(0.5,x(hi)-x(lo)),height:h,fill,opacity,rx:2});svg.append(r);return r}
function tip(node,text){if(!node)return;node.addEventListener('mouseenter',()=>{$('tooltip').textContent=text;$('tooltip').style.display='block'});node.addEventListener('mousemove',e=>{$('tooltip').style.left=Math.min(e.clientX+15,window.innerWidth-490)+'px';$('tooltip').style.top=Math.min(e.clientY+15,window.innerHeight-180)+'px'});node.addEventListener('mouseleave',()=>{$('tooltip').style.display='none'});}
function pointAt(pool,t){let lo=0,hi=pool.points.length;while(lo<hi){const m=(lo+hi)>>1;if(pool.points[m].seconds<=t)lo=m+1;else hi=m}return pool.points[Math.max(0,lo-1)]}
function cursorAt(t){cursor=t;document.querySelectorAll('.time-cursor').forEach(line=>{line.setAttribute('x1',x(t));line.setAttribute('x2',x(t));line.style.display='block'});const lines=[ms(t)];for(const pool of stats.pools){const p=pointAt(pool,t);lines.push(`${pool.pool}: ${bytes(p.total_bytes)} allocated · ${bytes(p.active_bytes)} in use`);lines.push('  '+Object.entries(p.by_component).filter(([,v])=>v).map(([k,v])=>`${k} ${bytes(v)}`).join(' · '));}$('cursor-info').textContent=lines.join('\n');}
function linkCursor(svg,height){const line=el('line',{class:'time-cursor',x1:0,x2:0,y1:10,y2:height-30,stroke:'#142e3c','stroke-width':1,'stroke-dasharray':'4 3','pointer-events':'none',style:'display:none'});svg.append(line);svg.addEventListener('mousemove',e=>{const box=svg.getBoundingClientRect(),px=(e.clientX-box.left)/box.width*W;if(px>=LEFT&&px<=W-RIGHT)cursorAt(start+(px-LEFT)/PLOT*(end-start));});}
function sampleTimes(pool){return [start,...pool.points.map(p=>p.seconds).filter(t=>t>start&&t<end),end]}
function stepPath(times,value,y){let d='';times.forEach((t,i)=>{const px=x(t),py=y(value(pointAt(this,t)));d+=i?` H${px} V${py}`:`M${px},${py}`});return d}
function legend(parent,names){const box=html('div',undefined,'legend');for(const name of names){const label=html('span');const sw=html('i',undefined,'swatch');sw.style.background=color(name);label.append(sw,document.createTextNode(name));box.append(label)}parent.append(box)}
function renderOperations(){const lanes=[...new Set(trace.operations.filter(o=>o.kind!=='control').map(o=>o.kind+': '+o.resources.join(' + ')))].sort((a,b)=>(a.startsWith('compute')?0:1)-(b.startsWith('compute')?0:1)||a.localeCompare(b));const height=70+lanes.length*38,svg=frame(height);axes(svg,12,height-32);
 const pool=stats.pools.find(p=>p.pool===$('backdrop').value);if(pool&&$('show-backdrop').checked&&pool.peak_bytes){const ts=sampleTimes(pool),base=height-34,scale=v=>base-v/pool.peak_bytes*(base-14);const d=stepPath.call(pool,ts,p=>p.total_bytes,scale)+` L${x(end)},${base} L${x(start)},${base} Z`;svg.append(el('path',{d,fill:'#137f7b',opacity:0.09}));svg.append(el('text',{x:LEFT+8,y:21,fill:'#65827e'},`${pool.pool} backdrop · scaled to ${bytes(pool.peak_bytes)}`));}
 lanes.forEach((lane,i)=>{const y=32+i*38;svg.append(el('text',{x:LEFT-14,y:y+16,fill:'#40576a','text-anchor':'end'},lane));for(const op of trace.operations.filter(o=>o.kind+': '+o.resources.join(' + ')===lane)){const r=rect(svg,op.start_seconds,op.end_seconds,y,24,color(op.component));tip(r,`${op.name}\n${op.provenance}\n${ms(op.start_seconds)} → ${ms(op.end_seconds)} (${ms(op.end_seconds-op.start_seconds)})\n${op.details}`);if(r&&Number(r.getAttribute('width'))>72){const count=Math.floor((Number(r.getAttribute('width'))-10)/6.5);svg.append(el('text',{x:Number(r.getAttribute('x'))+5,y:y+16,fill:'white','pointer-events':'none'},op.component.length>count?op.component.slice(0,count-1)+'…':op.component));}}});linkCursor(svg,height);$('operations').replaceChildren(svg);}
function renderMemory(){const root=$('memory-panels');root.replaceChildren();for(const pool of stats.pools){const panel=html('section',undefined,'panel');panel.append(html('h2',pool.pool+' · allocated memory'));const subtitle=html('p',`Peak ${bytes(pool.peak_bytes)} at ${ms(pool.peak_seconds)} · Average ${bytes(pool.average_bytes)} · In-use peak ${bytes(pool.active_peak_bytes)}`,'muted');panel.append(subtitle);const height=265,top=16,bottom=226,svg=frame(height),maximum=Math.max(pool.peak_bytes,pool.capacity_bytes||0,1)*1.08,y=v=>bottom-v/maximum*(bottom-top),times=sampleTimes(pool);axes(svg,top,bottom);
 for(let i=0;i<=4;i++){const v=maximum*i/4;svg.append(el('text',{x:LEFT-14,y:y(v)+4,fill:'#647586','text-anchor':'end'},bytes(v)));}
 const names=Object.keys(pool.component_peak_bytes),prior=[];for(const name of names){const low=p=>prior.reduce((sum,n)=>sum+p.by_component[n],0),lower=times.map(t=>[x(t),y(low(pointAt(pool,t)))]),upper=times.map(t=>[x(t),y(low(pointAt(pool,t))+pointAt(pool,t).by_component[name])]);let d=`M${upper[0][0]},${upper[0][1]}`;for(let i=1;i<upper.length;i++)d+=` H${upper[i][0]} V${upper[i][1]}`;d+=` L${lower.at(-1)[0]},${lower.at(-1)[1]}`;for(let i=lower.length-2;i>=0;i--)d+=` V${lower[i][1]} H${lower[i][0]}`;d+=' Z';svg.append(el('path',{d,fill:color(name),opacity:0.8}));prior.push(name);}
 svg.append(el('path',{d:stepPath.call(pool,times,p=>p.active_bytes,y),fill:'none',stroke:'#263847','stroke-width':1.6,'stroke-dasharray':'5 3'}));
 if(pool.capacity_bytes){const cy=y(pool.capacity_bytes);svg.append(el('line',{x1:LEFT,x2:W-RIGHT,y1:cy,y2:cy,stroke:'#be583c','stroke-dasharray':'6 4'}));svg.append(el('text',{x:W-RIGHT-4,y:cy-6,fill:'#be583c','text-anchor':'end'},`Capacity ${bytes(pool.capacity_bytes)}`));}
 linkCursor(svg,height);const chart=html('div',undefined,'chart');chart.append(svg);panel.append(chart);legend(panel,names);panel.append(html('p','Dashed dark line: allocations currently in use. Stacked areas: physical allocations, including idle persistent buffers.','muted'));
 const table=html('table'),head=html('tr');['Component','At total peak','Own peak'].forEach((name,i)=>head.append(html('th',name,i?'num':'')));table.append(head);for(const name of names){const row=html('tr');row.append(html('td',name),html('td',bytes(pool.components_at_peak[name]),'num'),html('td',bytes(pool.component_peak_bytes[name]),'num'));table.append(row)}panel.append(table);if(pool.capacity_bytes&&pool.peak_bytes>pool.capacity_bytes)panel.append(html('p','This candidate exceeds the declared capacity.','warning'));root.append(panel);}}
function renderLifetimes(){const pool=$('lifetime-pool').value,query=$('buffer-filter').value.toLowerCase(),rows=trace.buffers.filter(b=>b.pool===pool&&(b.name+' '+b.component).toLowerCase().includes(query)&&b.end_seconds>start&&b.start_seconds<end);const height=60+rows.length*25,svg=frame(Math.max(90,height));axes(svg,8,height-30);rows.forEach((b,i)=>{const y=10+i*25;svg.append(el('text',{x:LEFT-14,y:y+14,fill:'#40576a','text-anchor':'end'},b.name.length>28?b.name.slice(0,26)+'…':b.name));const r=rect(svg,b.start_seconds,b.end_seconds,y,18,color(b.component),0.22);const message=`${b.name}\n${b.component} · ${b.pool} · owner: ${b.owner}\n${bytes(b.allocated_bytes)} allocated (${bytes(b.size_bytes)} payload)\n${ms(b.start_seconds)} → ${ms(b.end_seconds)}\n${b.persistent?'Persistent; lifetime clipped to report window':'Transient'}`;tip(r,message);for(const [a,z] of b.active_intervals)tip(rect(svg,a,z,y,18,color(b.component)),message);});linkCursor(svg,height);$('lifetimes').replaceChildren(svg);}
function redraw(){start=trace.duration_seconds*Number($('range-start').value)/100;end=trace.duration_seconds*Number($('range-end').value)/100;renderOperations();renderMemory();renderLifetimes();if(cursor!==null&&cursor>=start&&cursor<=end)cursorAt(cursor);}
function card(label,value,detail){const c=html('div',undefined,'card');c.append(html('span',label),html('strong',value),html('small',detail));$('cards').append(c)}
function load(index){({trace,stats}=DATA.candidates[index]);cursor=null;$('status').textContent=trace.source.toUpperCase();$('cards').replaceChildren();if(DATA.candidates[index].objective_peak_bytes!==undefined)card('Optimization scope peak',bytes(DATA.candidates[index].objective_peak_bytes),(DATA.selection.objective_owners||['all owners']).join(' + '));card('End-to-end duration',ms(trace.duration_seconds),'Schedule completion, including I/O');for(const pool of stats.pools)card(pool.pool+' peak',bytes(pool.peak_bytes),'At '+ms(pool.peak_seconds)+(pool.capacity_bytes?' / capacity '+bytes(pool.capacity_bytes):''));card('Compute / I/O overlap',ms(stats.compute_io_overlap_seconds),((stats.compute_io_overlap_seconds/trace.duration_seconds)*100).toFixed(1)+'% of total time');for(const id of ['backdrop','lifetime-pool']){$(id).replaceChildren();for(const pool of trace.pools)option($(id),pool.name,pool.name);}
 $('assumptions').replaceChildren(...trace.assumptions.map(s=>html('li',s)));$('metadata').textContent=JSON.stringify({parameters:trace.metadata,profiles:[...new Set(trace.operations.map(op=>op.provenance))],resource_busy_seconds:stats.resource_busy_seconds},null,2);$('source-note').textContent=trace.source==='measured'?'Operation timestamps are measured on a common clock. Allocation sizes and lifetimes follow the supplied declarations; they are not process-memory samples.':'Predicted schedule and declared physical allocations. This report does not certify hardware throughput or whole-process memory.';
 const sel=DATA.selection;$('selection-note').textContent=sel.latency_limit_seconds?`Target: at least ${(sel.target_throughput_fraction*100).toFixed(1)}% of the fastest supplied candidate's predicted throughput; latency ≤ ${ms(sel.latency_limit_seconds)}. `+(sel.selected_index===null?'No candidate meets the target and all capacities.':'Minimum-memory eligible candidate: '+DATA.candidates[sel.selected_index].trace.name):'';$('cursor-info').textContent='Move over a chart to inspect all storage pools at the same time.';redraw();}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
DATA.candidates.forEach((c,i)=>option($('candidate'),i,(i===DATA.selection.selected_index?'★ ':'')+c.trace.name));$('candidate').value=DATA.selection.selected_index??0;
$('candidate').addEventListener('change',()=>load(Number($('candidate').value)));$('backdrop').addEventListener('change',redraw);$('show-backdrop').addEventListener('change',redraw);$('lifetime-pool').addEventListener('change',renderLifetimes);$('buffer-filter').addEventListener('input',renderLifetimes);
$('range-start').addEventListener('input',()=>{if(Number($('range-start').value)>=Number($('range-end').value))$('range-end').value=Number($('range-start').value)+1;redraw()});$('range-end').addEventListener('input',()=>{if(Number($('range-end').value)<=Number($('range-start').value))$('range-start').value=Number($('range-end').value)-1;redraw()});
$('reset').addEventListener('click',()=>{$('range-start').value=0;$('range-end').value=100;redraw()});$('json-export').addEventListener('click',()=>download('activation-timeline.json',JSON.stringify(DATA,null,2),'application/json'));
$('svg-export').addEventListener('click',()=>{const nodes=[...document.querySelectorAll('#operations svg, #memory-panels svg')],heights=nodes.map(n=>Number(n.viewBox.baseVal.height)),total=heights.reduce((a,b)=>a+b+40,0)+40,svg=frame(total);let offset=30;nodes.forEach((node,i)=>{const group=el('g',{transform:`translate(0 ${offset})`});group.append(el('text',{x:16,y:0,fill:'#172a3a'},i?stats.pools[i-1].pool:'Compute & I/O'));for(const child of node.childNodes)group.append(child.cloneNode(true));svg.append(group);offset+=heights[i]+40});svg.setAttribute('xmlns',NS);download('activation-timeline.svg',new XMLSerializer().serializeToString(svg),'image/svg+xml')});
load(Number($('candidate').value));
</script></body></html>"""
